# Exclusions from analysis (Automatic Analysis)
sonar.exclusions=**/db/migration/**/*.sql

# Exclusions for copy-paste detection (Automatic Analysis)
sonar.cpd.exclusions=**/db/migration/**/*.sql,**/fixtures/**
