sonar.projectKey=endurancecode_endurancetrio-community
sonar.host.url=https://sonarcloud.io

# Path to sources
sonar.sources=.
sonar.exclusions=**/db/migration/**/*.sql

# Path to tests
sonar.tests=.
#sonar.test.exclusions=
#sonar.test.inclusions=

# Coverage
sonar.coverage.exclusions=**/model/entity/**,**/model/enumerator/**,**/config/**
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
sonar.cpd.exclusions=**/db/migration/**/*.sql
