--
-- Copyright (c) 2011-2026 Ricardo do Canto
--
-- This file is part of the EnduranceTrio project.
--
-- Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
-- (the "License");
--
-- You may not use this file except in compliance with the License. You may obtain a copy
-- of the License at https://fsl.software/
--
-- THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
-- PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
--
-- IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
-- SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
-- EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
--

-- Description: Adds auditable columns to the EnduranceTrio application event domain tables
--

SET SCHEMA endurancetrio_hub;

ALTER TABLE event ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE event ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE event ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE organizer ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE organizer ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE organizer ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE age_group ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE age_group ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE age_group ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE aquabike_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE aquabike_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE aquabike_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE aquathlon_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE aquathlon_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE aquathlon_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE biathlon_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE biathlon_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE biathlon_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE double_biathlon_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE double_biathlon_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE double_biathlon_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE duathlon_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE duathlon_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE duathlon_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE single_sport_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE single_sport_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE single_sport_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE triathlon_distance ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE triathlon_distance ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE triathlon_distance ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE course ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE course ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE course ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE race ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE race ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE race ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE triathlon_based_race ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE triathlon_based_race ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE triathlon_based_race ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE event_file ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE event_file ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE event_file ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE results_file ADD COLUMN version    INTEGER   NOT NULL DEFAULT 0;
ALTER TABLE results_file ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE results_file ADD COLUMN updated_at TIMESTAMP;
