/*
 * Copyright (c) 2011-2026 Ricardo do Canto
 *
 * This file is part of the EnduranceTrio project.
 *
 * Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
 * (the "License");
 *
 * You may not use this file except in compliance with the License. You may obtain a copy
 * of the License at https://fsl.software/
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
 * PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
 *
 * IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
 * SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
 * EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
 */

/**
 * @file Generates src/scss/utilities/endurance-icons.scss from icons.config.json and
 *       source SVGs (either from @mdi/svg or custom files in src/icons/).
 *
 *       Each configured SVG is converted to a URL-encoded data URI and emitted as a
 *       CSS class (`.et-{name}`) that uses a `mask-image` approach so the icon
 *       inherits the current text color via `currentColor`.
 *
 *       Run directly:  node scripts/generate-icons.js
 *       Or via npm:    npm run generate:icons
 *       (prebuild:* hooks also run this before every webpack build)
 */

import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const configPath = resolve(ROOT, 'icons.config.json');
const outputPath = resolve(ROOT, 'src', 'scss', 'utilities',
    'endurance-icons.scss');

const config = JSON.parse(readFileSync(configPath, 'utf-8'));

function svgToDataUri(svgContent) {
  const data = svgContent
  .replace(/<!--.*?-->/gs, '')
  .replace(/>\s+</g, '><')
  .trim();
  const encoded = encodeURIComponent(data)
  .replace(/%20/g, ' ');
  return `url("data:image/svg+xml,${encoded}")`;
}

function readSvg(filePath) {
  return readFileSync(filePath, 'utf-8').trim();
}

const entries = [];

for (const name of config.mdi) {
  const svgPath = resolve(ROOT, 'node_modules', '@mdi', 'svg', 'svg',
      `${name}.svg`);
  const svg = readSvg(svgPath);
  entries.push({name: `et-${name}`, svg});
}

for (const [name, relativePath] of Object.entries(config.custom)) {
  const svgPath = resolve(ROOT, relativePath);
  const svg = readSvg(svgPath);
  entries.push({name: `et-${name}`, svg});
}

const lines = [
  '// Generated by scripts/generate-icons.js — do not edit directly',
  '',
  '@mixin et-icon-base {',
  '  display: inline-block;',
  '  width: 100%;',
  '  height: 100%;',
  '  background-color: currentColor;',
  '  mask-size: contain;',
  '  mask-repeat: no-repeat;',
  '  mask-position: center;',
  '  -webkit-mask-size: contain;',
  '  -webkit-mask-repeat: no-repeat;',
  '  -webkit-mask-position: center;',
  '  vertical-align: middle;',
  '}',
  '',
];

for (const {name, svg} of entries) {
  const dataUri = svgToDataUri(svg);
  lines.push(`.${name} {`);
  lines.push(`  @include et-icon-base;`);
  lines.push(`  mask-image: ${dataUri};`);
  lines.push(`  -webkit-mask-image: ${dataUri};`);
  lines.push(`}`);
  lines.push('');
}

const outputDir = dirname(outputPath);
if (!existsSync(outputDir)) {
  mkdirSync(outputDir, {recursive: true});
}

writeFileSync(outputPath, lines.join('\n'), 'utf-8');
console.log(`Generated ${entries.length} icon(s) — written to ${outputPath}`);
